export enum ChallengeType {
  EXECUTION_COOLER = 'EXECUTION_COOLER',
  EXECUTION_SHELVES = 'EXECUTION_SHELVES',
  EXECUTION_PTC = 'EXECUTION_PTC',
  EXECUTION_ACTIVATION = 'EXECUTION_ACTIVATION',
}
