export enum ChallengeExecutionMethod {
  TAKE_PHOTO = 'TAKE_PHOTO',
  MARK_COMPLETE = 'MARK_COMPLETE',
  PURCHASE = 'PURCHASE',
  PURCHASE_MULTIPLE = 'PURCHASE_MULTIPLE',
  PURCHASE_MULTIPLE_VOLUME_FIXED = 'PURCHASE_MULTIPLE_VOLUME_FIXED',
  PURCHASE_MULTIPLE_CURRENCY_FIXED = 'PURCHASE_MULTIPLE_CURRENCY_FIXED',
  MY_PROGRESS = 'MY_PROGRESS',
  PURCHASE_SINGLE_VOLUME_FIXED = 'PURCHASE_SINGLE_VOLUME_FIXED',
}
