export enum RewardsSettingType {
  DEFAULT_CONFIGURATION = 'DEFAULT_CONFIGURATION',
  FILTER = 'FILTER',
  TERMS = 'TERMS',
  CATEGORIES = 'CATEGORIES',
  RULES = 'RULES',
  BEES_BANK = 'BEES_BANK',
  BENEFITS_BANNER = 'BENEFITS_BANNER',
  HUB_HEADER = 'HUB_HEADER',
  ENROLLMENT_PAGE = 'ENROLLMENT_PAGE',
  TOGGLES = 'TOGGLES',
}
