export enum BeesEntity {
  ACCOUNTS = 'ACCOUNTS',
  DELIVERY_WINDOWS = 'DELIVERY_WINDOWS',
  DEALS = 'DEALS',
  PROMOTIONS = 'PROMOTIONS',
  REWARDS_SETTINGS = 'REWARDS_SETTINGS',
  SEGMENTATION = 'SEGMENTATION',
  CHALLENGES = 'CHALLENGES',
  ITEMS = 'ITEMS',
  PRODUCT_ASSORTMENT_INCLUSION = 'PRODUCT_ASSORTMENT_INCLUSION',
}
