/**
 * @monaco
 */
export enum BeesEntity {
  ACCOUNTS = 'ACCOUNTS',
  CONTRACTS = 'CONTRACTS',
  CREDITS = 'CREDITS',
  DELIVERY_WINDOWS = 'DELIVERY_WINDOWS',
  DEALS = 'DEALS',
  PROMOTIONS = 'PROMOTIONS',
  REWARDS_SETTINGS = 'REWARDS_SETTINGS',
  SEGMENTATION = 'SEGMENTATION',
  CHALLENGES = 'CHALLENGES',
  ITEMS = 'ITEMS',
  PRODUCT_ASSORTMENT_INCLUSION = 'PRODUCT_ASSORTMENT_INCLUSION',
  BEES_STORAGE = 'BEES_STORAGE',
  CMS_STORAGE = 'CMS_STORAGE',
  ORDERS = 'ORDERS',
  INVENTORY = 'INVENTORY',
  CATEGORIES = 'CATEGORIES',
  PRICES = 'PRICES',
  DATA_RECOMMENDATION = 'DATA_RECOMMENDATION',
  GROW = 'GROW',
  INVOICES = 'INVOICES',
  NON_REQUEST_TEMPLATE = 'NON_REQUEST_TEMPLATE',
  VENDOR = 'VENDOR',
  RATINGS = 'RATINGS',
}
