export enum BeesEntity {
  ACCOUNTS = 'ACCOUNTS',
  DEALS = 'DEALS',
  PROMOTIONS = 'PROMOTIONS',
  REWARDS_SETTINGS = 'REWARDS_SETTINGS',
  ITEMS = 'ITEMS',
  PRODUCT_ASSORTMENT_INCLUSION = 'PRODUCT_ASSORTMENT_INCLUSION',
}
