export enum DealType {
  PRICE_REDUCTION = 'PRICE_REDUCTION',
  REFERRAL_COUPON = 'REFERRAL_COUPON',
  REWARD_COUPON = 'REWARD_COUPON',
  UNDEFINED = 'UNDEFINED',
  SPECIAL_OFFERS = 'SPECIAL_OFFERS',
  POSTOFF = 'POSTOFF',
}
