/**
 * @monaco
 */
export enum DealOutputType {
  PALLET_DISCOUNT = 'PALLET_DISCOUNT',
  REGULAR_DISCOUNT = 'REGULAR_DISCOUNT',
  ORDER_DISCOUNT = 'ORDER_DISCOUNT',
  FREE_GOOD = 'FREE_GOOD',
  FLEXIBLE_DISCOUNT = 'FLEXIBLE_DISCOUNT',
  SCALED_DISCOUNT = 'SCALED_DISCOUNT',
  SCALED_FREE_GOOD = 'SCALED_FREE_GOOD',
  SPECIAL_OFFERS = 'SPECIAL_OFFERS',
}

/**
 * Actual values in deal service as of 2025/07/30
 */
// DISCOUNT,
//   STEPPED_DISCOUNT,
//   FREE_GOOD,
//   STEPPED_FREE_GOOD,
//   STEPPED_FREE_GOOD_BY_AMOUNT,
//   FLEXIBLE_DISCOUNT,
//   STEPPED_FLEXIBLE_DISCOUNT,
//   STEPPED_FLEXIBLE_DISCOUNT_BY_AMOUNT,
//   FIXED_COMBO,
//   ORDER_TOTAL,
//   STEPPED_ORDER_TOTAL,
//   PALLET_DISCOUNT,
//   STEPPED_SKU_POOL_DISCOUNT,
//   POSTOFF,
//   SPECIAL_OFFERS,
//   PRICE_REDUCTION,
//   FLASH_PROMO,
//   CHARGE_DISCOUNT,
//   MANUAL_DISCOUNT;
