/**
 * @monaco
 */
export enum DealOutputType {
  PALLET_DISCOUNT = 'PALLET_DISCOUNT',
  REGULAR_DISCOUNT = 'REGULAR_DISCOUNT',
  ORDER_DISCOUNT = 'ORDER_DISCOUNT',
  FREE_GOOD = 'FREE_GOOD',
  FLEXIBLE_DISCOUNT = 'FLEXIBLE_DISCOUNT',
  SCALED_DISCOUNT = 'SCALED_DISCOUNT',
  SCALED_FREE_GOOD = 'SCALED_FREE_GOOD',
  SPECIAL_OFFERS = 'SPECIAL_OFFERS',
}
