export enum CategoryFilenameMatchStrategy {
  EXACT_MATCH = 'EXACT_MATCH',
  CATEGORY_CONTAINS = 'CATEGORY_CONTAINS',
  CATEGORY_STARTS_WITH = 'CATEGORY_STARTS_WITH',
  FILENAME_CONTAINS = 'FILENAME_CONTAINS',
  FILENAME_STARTS_WITH = 'FILENAME_STARTS_WITH',
}
