/**
 * @monaco
 */
export enum PlatformIdType {
  COMBO = 'COMBO',
  CONTRACT = 'CONTRACT',
  ENFORCEMENT = 'ENFORCEMENT',
  ENFORCEMENT_V2 = 'ENFORCEMENT_V2',
  ENFORCEMENT_GENERAL = 'ENFORCEMENT_GENERAL',
  ITEM = 'ITEM',
  INVENTORY = 'INVENTORY',
  PROMOTION = 'PROMOTION',
  DELIVERY_CENTER = 'DELIVERY_CENTER',
  ASSORTMENT_GENERAL = 'ASSORTMENT_GENERAL',
  ASSORTMENT_INCLUSION = 'ASSORTMENT_INCLUSION',
  ASSORTMENT_UNAVAILABLE = 'ASSORTMENT_UNAVAILABLE',
  COMBO_ACCOUNT = 'COMBO_ACCOUNT',
  COMBO_DELIVERY = 'COMBO_DELIVERY',
  EMPTIES = 'EMPTIES',
}
