/**
 * @monaco
 */
export enum PromoType {
  STEPPED_DISCOUNT = 'STEPPED_DISCOUNT',
  STEPPED_FREE_GOOD = 'STEPPED_FREE_GOOD',
  DISCOUNT = 'DISCOUNT',
  FREE_GOOD = 'FREE_GOOD',
  FLEXIBLE_DISCOUNT = 'FLEXIBLE_DISCOUNT',
  FIXED_COMBO = 'FIXED_COMBO',
}
